### ISSUE TITLE
Screen Update Error CTD

### ISSUE THREAD

**Issue by ryu777mtg** [TheLMiffy1111/PackagedAvaritia#1]
When trying to Encode the Eternal Singularity with the Compound Singularities it does not register as a Crafting Recipe but it does trigger as a Ore Processing Recipe however it is not an Ore Processing Recipe and thus switching back and forth from the two methods causes the game crash.

Here is the entire crash log:
https://pastebin.com/21KcqGFS

If there is anything else I can provide to help with the issue or if I need to take this over to the Eternal Singularity mod authors let me know.

**Comment by TheLMiffy1111** [comment]
Please take this issue over to Eternal Singularity, their recipes don't have a name.

**Comment by TheLMiffy1111** [comment]
I'll add a check to avoid this crash next version.
